name: Build
on:
  push:
  pull_request:
  schedule:
  - cron: 0 3 * * 6  # Every Saturday at 3:00 AM
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Compile cover letter
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cover.tex
